apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: argocd-helm-nginx/helm
    repoURL: https://github.com/D-Bhatta/python-helloworld-test-build
    targetRevision: HEAD
